### ISSUE TITLE
パーソナルデータ連携モジュール pxr-operator-service ビルド手順書の修正

### ISSUE THREAD

**Issue by itoshot** [Personal-Data-Linkage-Module/docs#11]
```[tasklist]
### Tasks
- [ ] https://github.com/Personal-Data-Linkage-Module/docs/issues/12
- [ ] https://github.com/Personal-Data-Linkage-Module/docs/issues/13
- [ ] https://github.com/Personal-Data-Linkage-Module/docs/issues/14
- [ ] https://github.com/Personal-Data-Linkage-Module/docs/issues/15
```
