### ISSUE TITLE
パーソナルデータ連携モジュール構築ガイドの記述修正

### ISSUE THREAD

**Issue by itoshot** [Personal-Data-Linkage-Module/docs#16]
## 修正対象
[パーソナルデータ連携モジュール 構築ガイド](https://github.com/Personal-Data-Linkage-Module/docs/blob/develop/%E5%B0%8E%E5%85%A5%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3/linkage_build_guide.md)
```[tasklist]
### Tasks
- [ ] 2章5節の「証明書とRSA鍵のSecretを作成」項に「SSL 自己証明書でも問題ない」旨を追記
- [ ] 2章5節の「Deployment編集」項に「{イメージ名}:{タグ}の置換例}」を追記
- [ ] 2章7節「初期カタログの投入」不足ドキュメントを追記
- [ ] common-configmap.yaml の修正タイミングを追記
```
